### PR TITLE
WCAG!

### PR DESCRIPTION
**Pull request by contolini**
Due to unforeseen git history woes, the initial commit has been force pushed to upstream. Please review the code that's there and provide any feedback. This PR updates the docs and adds a screenshot.
## What is this thing?

It's a command line tool (and node module) that uses the [AChecker API](http://achecker.ca/documentation/web_service_api.php) to check HTML for accessibility problems. It was created to let Travis run accessibility tests automatically against Capital Framework components but it can be used to test any website.
## Testing

See https://github.com/contolini/node-wcag#contributing
## Review
- @imuchnik  
- @Scotchester 
- @anselmbradford 
- @ascott1

### CODE REVIEW

**Comment by contolini** [comment]
Ignore Travis. He's unable to read the encrypted key in `.travis.yml` because this PR is coming from a fork. In the future I'll submit PRs [from a branch of this repo](http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests).

**Comment by imuchnik** [comment]
:+1:

**Comment by ascott1** [comment]
So very excited about this. Looks good!

**Comment by anselmbradford** [comment]
noice!

**Pull request merged**
